status = error
name = QuietSparkLogging

appender.console.type = Console
appender.console.name = Console
appender.console.target = SYSTEM_ERR
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{HH:mm:ss} %-5p %c{1}: %m%n

rootLogger.level = error
rootLogger.appenderRef.console.ref = Console

logger.spark.name = org.apache.spark
logger.spark.level = error

logger.hadoop.name = org.apache.hadoop
logger.hadoop.level = error

logger.jetty.name = org.eclipse.jetty
logger.jetty.level = error

logger.akka.name = akka
logger.akka.level = error

logger.netlib.name = dev.ludovic.netlib
logger.netlib.level = error
